export const env = {
  PORT: Number(process.env.PORT || 8080),
  CORS_ORIGIN: process.env.CORS_ORIGIN || '',
  MONGODB_URI: process.env.MONGODB_URI || '',
  GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
  GEMINI_MODEL: process.env.GEMINI_MODEL || 'gemini-3.1-flash-lite-preview',
  GEMINI_CACHE_TTL_SECONDS: 3600,
  GEMINI_PROXY_TIMEOUT_MS: Number(process.env.GEMINI_PROXY_TIMEOUT_MS || 55000),
  GEMINI_CACHE_MIN_CHARS: Number(process.env.GEMINI_CACHE_MIN_CHARS || 2000),
  SESSION_SECRET: process.env.SESSION_SECRET || 'hajimi-dev-session-secret',
  SESSION_EXPIRES_IN: process.env.SESSION_EXPIRES_IN || '12h',
  API_RATE_LIMIT_WINDOW_MS: Number(process.env.API_RATE_LIMIT_WINDOW_MS || 5 * 60 * 1000),
  API_RATE_LIMIT_MAX: Number(process.env.API_RATE_LIMIT_MAX || 30),
  S3_BUCKET: process.env.S3_BUCKET || '',
  S3_REGION: process.env.S3_REGION || 'auto',
  S3_ENDPOINT: process.env.S3_ENDPOINT || '',
  S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID || '',
  S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY || '',
  S3_PUBLIC_BASE_URL: process.env.S3_PUBLIC_BASE_URL || '',
  STORAGE_MODE: process.env.STORAGE_MODE || '',
};
